Добавил проверку символов в пароле
itstep-shambala/ManageUser pull request #4
Opened 2021-03-30 20:19 UTC by alexeylevashev

Добавил проверку пароля на символы (минимальная длина, количество заглавных букв, строчных букв, чисел и спец. символов > 1, алфавит - кириллица или латиница)

2021-03-30 20:19 UTC, alexeylevashev commented
![](https://github.trello.services/images/mini-trello-icon.png) [#task_check_password Проверка пароля на соответствие требованиям](https://trello.com/c/U3jDJNfH/6-taskcheckpassword-%D0%BF%D1%80%D0%BE%D0%B2%D0%B5%D1%80%D0%BA%D0%B0-%D0%BF%D0%B0%D1%80%D0%BE%D0%BB%D1%8F-%D0%BD%D0%B0-%D1%81%D0%BE%D0%BE%D1%82%D0%B2%D0%B5%D1%82%D1%81%D1%82%D0%B2%D0%B8%D0%B5-%D1%82%D1%80%D0%B5%D0%B1%D0%BE%D0%B2%D0%B0%D0%BD%D0%B8%D1%8F%D0%BC)

2021-04-04 07:13 UTC, GVFedosenko approved these changes
Cool!!!

2021-04-04 09:33 UTC, anst-foto requested changes
Доработать с учётом комментариев и предложений.

Желательно проверки требований пароля разделить на несколько функций, сделать проверку на соответствие минимальному количеству, которое заложено в классе `PasswordRules`

2021-04-04 09:33 UTC, anst-foto commented on CheckPassword/CheckPassword.cs
> +        public int PasswordCheck(string password)
Возврат результата функции лучше делать через `bool`

2021-04-04 09:33 UTC, anst-foto commented on CheckPassword/CheckPassword.cs
> +            using (var file = new FileStream("PasswordRules.json", FileMode.Open))
```suggestion
            using (var file = new FileStream(path, FileMode.Open))
```

2021-04-04 09:33 UTC, anst-foto commented on CheckPassword/CheckPassword.cs
> +        public PasswordRules importRules()
```suggestion
        public PasswordRules importRules(string path)
```

2021-04-04 09:33 UTC, anst-foto commented on CheckPassword/CheckPassword.cs
> +            rules = importRules();
```suggestion
            var rules = importRules();
```

2021-04-04 09:33 UTC, anst-foto commented on CheckPassword/CheckPassword.cs
> +            string pass = password;
Для чего?

2021-04-04 09:33 UTC, anst-foto commented on CheckPassword/CheckPassword.cs
> +                }
Лучше отказаться от кодировочных таблиц, а использовать сравнение именно с наборами символов.

2021-04-04 09:33 UTC, anst-foto commented on CheckPassword/CheckPassword.cs
> +                if (pass.Length >= rules.MinLen & capLetterCount != 0 & smallLetterCount != 0 & intCount != 0 &
```suggestion
                if (pass.Length >= rules.MinLen && capLetterCount != 0 && smallLetterCount != 0 && intCount != 0 &&
```

2021-04-04 09:33 UTC, anst-foto commented on CheckPassword/CheckPassword.cs
> +                }
Желательно каждую проверку вынести в отдельный метод

2021-04-04 21:04 UTC, closed without merging