#task_registration_account
itstep-shambala/ManageUser pull request #5
Opened 2021-04-03 20:22 UTC by SushkowAndrey

Не получилось добавлять данные в таблицу table_account, выходит ошибка - Cannot add or update a child row: a foreign key constraint fails

2021-04-03 20:23 UTC, SushkowAndrey commented
![](https://github.trello.services/images/mini-trello-icon.png) [#task_registration_account Регистрация нового аккаунта](https://trello.com/c/86XdHoK1/4-taskregistrationaccount-%D1%80%D0%B5%D0%B3%D0%B8%D1%81%D1%82%D1%80%D0%B0%D1%86%D0%B8%D1%8F-%D0%BD%D0%BE%D0%B2%D0%BE%D0%B3%D0%BE-%D0%B0%D0%BA%D0%BA%D0%B0%D1%83%D0%BD%D1%82%D0%B0)

2021-04-04 06:38 UTC, anst-foto commented
> Не получилось добавлять данные в таблицу table_account, выходит ошибка - Cannot add or update a child row: a foreign key constraint fails

Пробовали отключить/убрать внешние ключи?

2021-04-04 07:07 UTC, GVFedosenko approved these changes
Cool!!!

2021-04-04 09:51 UTC, anst-foto requested changes
Переделать согласно комментариям

2021-04-04 09:51 UTC, anst-foto commented on ModelData/DBConnect.cs
> +        string conn_str = "Server=mysql60.hostland.ru;Database=host1323541_itstep37;Uid=host1323541_itstep;Pwd=269f43dc;";
Строку подключения лучше формировать из аргументов или из файла

2021-04-04 09:51 UTC, anst-foto commented on ModelData/DBConnect.cs
> +            connection.Open();
Не самый хороший вариант.

2021-04-04 10:01 UTC, closed without merging